version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: healthenv
      POSTGRES_PASSWORD: healthenv
      POSTGRES_DB: healthenv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - healthenv-network

  database_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: healthenv
      POSTGRES_PASSWORD: healthenv
      POSTGRES_DB: healthenv_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - healthenv-network

networks:
  healthenv-network:

volumes:
  pgdata:
  pgdata_test:


